[pyrogram]
api_id = 0
api_hash = ""
phone_number = "+39 1234567890"

[updates]
# you can decide whether to answer to updates coming from private or group chats
private_chats = true
group_chats = false

# when this is true, all the settings below will be ignored: all known updates will be answered
all_types = false

# these are the most common
typing = true
record_audio = true # voice messages
record_round = true # video messages

# other updates
upload_photo = false
upload_video = false
upload_audio = false
upload_document = false
upload_round = false
record_video = false
geo_location = false
game_play = false
choose_contact = false
